### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by gdagitrep** [tianhaoz95/fastlane-plugin-flutter_version#138]
**Describe the bug**

1. Installation using 
`gem install fastlane-plugin-flutter_version --version "1.0.0" --source "https://rubygems.pkg.github.com/tianhaoz95"` 

results in 

`bad response Unauthorized 401 (https://rubygems.pkg.github.com/tianhaoz95/specs.4.8.gz)`

2. Installing using `gem install fastlane-plugin-flutter_version` succeeds but when used in fastlane file, I get `Could not find action, lane or variable 'flutter_version'.` 

Awesome work to solve the problem though!

**Comment by tianhaoz95** [comment]
Thanks for reporting the critical issue. Hmmm I wonder if a recent push removed the version... would you mind sharing your project setup, for example, `Gemfile`. If you don't mind and the project is open source, a pointer to the repository will be helpful for pinning down the issue as well.

**Comment by tianhaoz95** [comment]
Actually, I should have some time to test it out in 40 minutes when I take the lunch break from work :)

**Comment by tianhaoz95** [comment]
Ah I just notice that the authentication error is coming from GitHub registry. Unlike RubyGem, the GitHub registry is more strict on authentication meaning that you need to authenticate with your GitHub account to download packages. See https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry#authenticating-to-github-packages for more details.

Basically you have 2 options:

1. Use GitHub registry and authenticate with your GitHub authentication following the instructions in https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry#installing-a-package. This approach is more secure in terms of source control.
2. Use the version from RubyGem like you tried.

The fastlane not finding the plugin seem to be a separate problem. For that, can you check if a line that looks like `gem 'fastlane-plugin-flutter_version', '~> 1.0', '>= 1.0.1'` is found in your `Gemfile` after the installation? In general, the project's Fastlane directory should more or less look something like https://github.com/tianhaoz95/fastlane-plugin-flutter_version/tree/master/regression

**Comment by gdagitrep** [comment]
Thanks for answers. 

Surprisingly, with the (2) method that I mentioned above, the `Gemfile` didn't get updated. I have manually added this line `gem 'fastlane-plugin-flutter_version', '~> 1.0', '>= 1.0.1'` to it now, and I will git it a try. Thanks again for prompt replies.

**Comment by tianhaoz95** [comment]
My best guess is that it's been added to a separate project by accident or globally. Please check if adding it to `Gemfile` and do a `bundle install` works.

**Comment by tianhaoz95** [comment]
Close for now. Please reopen if the fix doesn't work.
