### ISSUE TITLE
Example for iOS

### ISSUE THREAD

**Issue by davidbrenner** [tianhaoz95/fastlane-plugin-flutter_version#37]
Hi, 

I found this via your [medium article](https://medium.com/better-programming/build-a-fastlane-plugin-for-flutter-version-management-from-scratch-5df82bce391f). Thanks for the plugin, it looks great! 

Do you have an example of how to use this for iOS?

Additionally, do you have suggestions for how to keep version numbers sync'd? 

Even with CI, a number of times I've forgotten to bump the version number (even in pubspec.yaml). One option that I've considered is pulling the latest build number from the play/app store (ie: https://docs.fastlane.tools/actions/latest_testflight_build_number/) and then adding a script and/or plugin to write this back to pubspec.yaml. Is that something you'd be interested in?

**Comment by tianhaoz95** [comment]
>I found this via your medium article. Thanks for the plugin, it looks great!

Thanks!

>Do you have an example of how to use this for iOS?

Yes I think I once used it in both Android and iOS before I decided $99 a year wasn't a trivial number. Let me dig that out from my memory.

>Additionally, do you have suggestions for how to keep version numbers sync'd?

Can you elaborate a bit on in which way do you want the version to be sync'd? If you have a pure Flutter application, both Android and iOS will be getting their version from `pubspec.yaml` which should be in sync. In addition, if you also have a backend for your app, maybe what you had in mind was keeping server API version and app version in sync?

>Even with CI, a number of times I've forgotten to bump the version number (even in pubspec.yaml). One option that I've considered is pulling the latest build number from the play/app store (ie: https://docs.fastlane.tools/actions/latest_testflight_build_number/) and then adding a script and/or plugin to write this back to pubspec.yaml. Is that something you'd be interested in?

Yes, pulling version number back is an interesting idea, the main reason for not taking advantage of that API is: 1. it's inconsistent between Android and iOS. 2. Always incrementing version by a patch/minor/major isn't meaningful for the user to understand why the version is changing.

However, it would be great if the version number advancement comes from the commit history.

It sounds a bit like https://github.com/semantic-release/semantic-release. Actually, I have considered building some kind of integration for auto version generation where it pulls the previous version and then increment base on commit messages where a chore/fix/bugfix is a patching, minor/feat/feature is a minor and major is a major.

**Comment by tianhaoz95** [comment]
@all-contributors please add davidbrenner for ideas

**Comment by tianhaoz95** [comment]
@davidbrenner If the iOS code works for you, maybe open a PR to list it in the README when you have some time. I'm sure there are iOS focus projects will appreciate it.

**Comment by davidbrenner** [comment]
I ran into issues just setting the version/build number in `upload`, so I ended up using the following, which worked brilliantly and is the same process I use for setting the build number/version in Xcode manually:

```
    # https://docs.fastlane.tools/actions/increment_version_number/
    increment_version_number(
      xcodeproj: "Runner.xcodeproj",
      version_number: flutter_version()["version_name"] # Set a specific version number
    )
    # https://docs.fastlane.tools/actions/increment_build_number/
    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: flutter_version()["version_code"] # Set a specific build number
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Alpha", export_method: "app-store")
    upload_to_testflight
``

Other flutter apps/devs may not be using schemes (or may be uploading directly to the app store rather than testflight), so those final two lines may need to change for them.

I'll open a PR for the README with this.

**Comment by davidbrenner** [comment]
PR for README: https://github.com/tianhaoz95/fastlane-plugin-flutter_version/pull/39

**Comment by tianhaoz95** [comment]
Thanks! Closing this in favor of #40

**Comment by tianhaoz95** [comment]
@all-contributors please add davidbrenner for doc
