### ISSUE TITLE
[BUG] codecov somehow tracks files outside lib???

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/fastlane-plugin-flutter_version#67]

**Comment by thomasrockhu** [comment]
@tianhaoz95, can you open a ticket in our [community boards](https://community.codecov.io), and I can try to take a look?

**Comment by tianhaoz95** [comment]
Thanks! Opened a topic in https://community.codecov.io/t/codcov-not-tracks-ignored-files-in-my-ruby-project/2416

**Comment by tianhaoz95** [comment]
Opened https://github.com/simplecov-ruby/simplecov/issues/975 to track.

**Comment by tianhaoz95** [comment]
That is WAI, I think marking it as ignore is good enough for now, open a new issue to track migration to `add_filter`.
