### ISSUE TITLE
gradlew file missing

### ISSUE THREAD

**Issue by RtypeStudios** [tianhaoz95/fastlane-plugin-flutter_version#71]
When using the fastlane-plugin-flutter_version plugin with the below fastlane file:

    desc "Submit a new Build"
    lane :build do

      gradle(
        task: "bundle",
        build_type: "Release",
      )
    end

I get the error: 

    Couldn't find gradlew at path '/Users/appveyor/projects/experimental/demo/android/gradlew'

And sure enough the gradlew is missing from the repo. But that is because a lot of git ignore files seem to suggest you should be excluding the gradlew file in source control and that it should be generated by flutter. 

Example of an ignore file excluding it: https://gist.github.com/Cheesetouched/ace446b9e6bedef76eb4fb7afb1ea164

A solution I came up with is to call flutter and the causes the gradlew to be created:

    Dir.chdir "../.." do
       sh("flutter", "build", "appbundle", "--release")
    end

But shouldn't the plugin do that automatically? Or am I missing something? (most likely :))

**Comment by tianhaoz95** [comment]
IIUC, per Flutter Fastlane integration guide (https://flutter.dev/docs/deployment/cd), `flutter build` is required before running lane to generate metafiles which include `gradlew` you mentioned (and also signing files as far as I remember):

![Screenshot from 2020-12-18 11-48-52](https://user-images.githubusercontent.com/16887772/102655375-0fd3c980-4127-11eb-91c0-c20b08154f4a.png)

The `flutter_version` plugin only retrieves the version information without building the app.

It is technically possible for `gradle(task: 'bundle', build_type: 'Release')` to do that, but the `gradle` action is an Android action that ideally shouldn't know anything about Flutter. If it looks for a parent Flutter project and builds as you described, it with add overhead or crash for non-Flutter Android projects.

Please let me know if the answer wasn't helpful or in the wrong direction.

**Comment by tianhaoz95** [comment]
@all-contributors please add RtypeStudios for question

**Comment by RtypeStudios** [comment]
My sincere apologies. I overlooked the fact the plugin is called "Flutter_Version" for some reason looking at the examples I made the assumption that it also did the building.

I must say I'm extremely impressed with your response and feel this is certainly a behaviour many other projects could learn from. Massive Kudos.

My only suggestion to help future flutter newbies like myself would be perhaps to include a line in the two examples, something like:

    desc "submit to internal track in Google Play Store"
    lane :internal do
      Dir.chdir "../.." { sh("flutter", "build", "appbundle", "--release") } # Call Flutter Build
      gradle(task: 'bundle', build_type: 'Release')
      upload_to_play_store(
        track: 'internal',
        version_code: flutter_version()["version_code"],
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_screenshots: true,
        skip_upload_images: true
      )
    end

    desc "submit to TestFlight"
    lane :internal do
      Dir.chdir "../.." { sh("flutter", "build", "ios", "--release", "--no-codesign") } # Call Flutter Build
      # https://docs.fastlane.tools/actions/increment_version_number/
      increment_version_number(
        xcodeproj: "Runner.xcodeproj",
        version_number: flutter_version()["version_name"] # Set a specific version number
      )
        # https://docs.fastlane.tools/actions/increment_build_number/
      increment_build_number(
        xcodeproj: "Runner.xcodeproj",
        build_number: flutter_version()["version_code"] # Set a specific build number
      )
      build_app(workspace: "Runner.xcworkspace", export_method: "app-store")
      upload_to_testflight
    end

totally up to you and I would be more than happy to do this as a PR if you would like.

**Comment by tianhaoz95** [comment]
@RtypeStudios I think what you wrote is good enough to be directly ported into the docs. Really appreciate it if you can open a PR to add that (I'm struggling with some work stuff recently).

**Comment by RtypeStudios** [comment]
Done. Give me a shout if there are any issues and thanks for providing such a useful tool!

**Comment by tianhaoz95** [comment]
@all-contributors please add RtypeStudios for doc

**Comment by KingIdee** [comment]
If you setup flavors on your android app;

```
  Dir.chdir "../.." { sh("flutter", "build", "appbundle", "--release") } # Call Flutter Build
```

Will always fail, particularly, it will give this error:

```
Gradle build failed to produce an .aab file. It's likely that this file was generated under /Users/idee/Documents/flutter-projects/yellowcard-mobile-app/build, but the tool couldn't find it.
```


So what's the alternative?

**Comment by tianhaoz95** [comment]
Hmmm... if you execute `flutter build appbundle --release` in the flutter project root, does it go through?

**Comment by tianhaoz95** [comment]
@KingIdee the behavior of flutter isn't the focus of this package, but I definitely want the instructions to be up-to-date and helpful. It will be really helpful if you can verify what the behavior of `flutter build appbunle` and `flutter build appbundle --release` is and paste the output here if possible so that I can take a look at what happened. Also, there are a few other contributors worked on this flow before, they can also add some input :)

**Comment by KingIdee** [comment]
The two commands return the same response.

```
idee@Idorenyins-MacBook-Pro mobile-app % flutter build appbundle --release

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        46.3s
Gradle build failed to produce an .aab file. It's likely that this file was generated under /Users/idee/Documents/flutter-projects/mobile-app/build, but the tool couldn't find it.


```



```
idee@Idorenyins-MacBook-Pro mobile-app % flutter build appbundle          

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        45.6s
Gradle build failed to produce an .aab file. It's likely that this file was generated under /Users/idee/Documents/flutter-projects/mobile-app/build, but the tool couldn't find it.
```

**Comment by tianhaoz95** [comment]
I haven't worked with apps with multiple favors in production environment, but as far as I know, if an app has production flavors, it must specific the flavor and target in `flutter run` and `flutter build` (or anywhere an aab or apk is built).

In that case, for

```bash
Dir.chdir "../.." { sh("flutter", "build", "appbundle", "--release") }
```

replacing it with

```bash
Dir.chdir "../.." { sh("flutter", "build", "appbundle", "--flavor", "production") }
```

should be fine since it's just a wrapper around a bash command.

However, for 

```bash
gradle(
  task: "bundle",
  build_type: "Release",
)
```

As it's a builtin action/lane from Fastlane framework, you will need to follow its options (see https://docs.fastlane.tools/actions/gradle for full documentation).

A quick scan finds that you might want to use:

```bash
gradle(
  task: "bundle",
  flavor: "production",
  build_type: "Release"
)
```

If that doesn't fit into your setup, then maybe you need to hack around with the `flags` option, although I'm sure that will be some hacky tweaks.

Please add the outputs from the experiments here :) It will be really helpful for me to update the documentation for other developers who are also using the flavor features.

**Comment by tianhaoz95** [comment]
Close for now. Reopen if the more fixes are needed.
