### ISSUE TITLE
Example for the "Available options"

### ISSUE THREAD

**Issue by M123-dev** [tianhaoz95/fastlane-plugin-flutter_version#77]
It would be nice to have a example for the "Available options", how to use them and for the `pubspec_location` which is the starting point.

**Comment by tianhaoz95** [comment]
Yes, that's a good idea.

Right away I remember that the `pubspec_location` is relative to the `Fastfile` (it's been a while, I will need to check).

I can add some examples for options right after I finish some mess things in my job (in a few days I guess).

At the same time, if you have some idea to add to the docs, please feel free to open a PR, I will arrange some time to merge them once I get the notification :)

**Comment by tianhaoz95** [comment]
@all-contributors please add @M123-dev for ideas

**Comment by tianhaoz95** [comment]
added some examples and details in #80 and #81.

**Comment by M123-dev** [comment]
@tianhaoz95 , thanks, this will help future devs a lot.
