### ISSUE TITLE
Syntax Error: There is this problem while running the fastlane LANE command 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [tianhaoz95/fastlane-plugin-flutter_version#87]
```
[12:10:49]:     34:         end
[12:10:49]:     35:         lane :dev do
[12:10:49]:  => 36:             Dir.chdir "../.." {sh("flutter", "build", "ios", "--release", "--no-codesign")}
[12:10:49]:     37:             increment_version_number(
[12:10:49]:     38:                 xcodeproj: "Runner.xcodeproj",

[!] Syntax error in your Fastfile on line 36: Fastfile:36: syntax error, unexpected '{', expecting end
        Dir.chdir "../.." {sh("flutter", "build", "ios",...
                          ^
Fastfile:36: syntax error, unexpected '}', expecting end
... "--release", "--no-codesign")}
...                              ^
Fastfile:56: syntax error, unexpected end, expecting end-of-input
    end
    ^~~

```

Looks like this one is not ` Dir.chdir "../.." {sh("flutter", "build", "ios", "--release", "--no-codesign")}` appropriate . Please help as soon as possible.

**Comment by tianhaoz95** [comment]
Oh, is it the iOS example?

@RtypeStudios are you familiar with the error message @ch-muhammad-adil posted?

Meanwhile, I will dig out my MacBook to investigate what might have happened.

**Comment by RtypeStudios** [comment]
@tianhaoz95 Yep, think so.

@ch-muhammad-adil can you try:

    Dir.chdir "../.." do sh("flutter", "build", "ios", "--release", "--no-codesign") end

using do and end instead of "{" and "}"

**Comment by ch-muhammad-adil** [comment]
Hey, thank you for responding I will check this out.

**Comment by tianhaoz95** [comment]
@RtypeStudios thanks for the suggestion!

@ch-muhammad-adil can you open a pull request to update the example in the docs as suggested after verifying that it solves the problem? I think do-end enclosure seem more readable in general.

**Comment by ch-muhammad-adil** [comment]
#88

**Comment by RtypeStudios** [comment]
@ch-muhammad-adil Thanks for fixing that up! Sorry, that brackets were my fault. I think originally that was on multiple lines and refactored it onto a single one.

**Comment by tianhaoz95** [comment]
@all-contributors please add @ch-muhammad-adil for doc

**Comment by tianhaoz95** [comment]
@all-contributors please add @ch-muhammad-adil for bug

**Comment by tianhaoz95** [comment]
@all-contributors please add @RtypeStudios for research

**Comment by tianhaoz95** [comment]
The update has been merged!

Thanks @RtypeStudios for the quick response! 

Thanks @ch-muhammad-adil for updating the docs!

**Comment by tianhaoz95** [comment]
@all-contributors please add @RtypeStudios for tutorial
