### ISSUE TITLE
Use correct iOS build command in README

### ISSUE THREAD

**Issue by lesliearkorful** [tianhaoz95/fastlane-plugin-flutter_version#95]
The iOS build command in the README is apparently android's.
`Dir.chdir "../.." do sh("flutter", "build", "appbundle", "--release") end # Call Flutter Build
`

This is what the Flutter website suggests for Fastlane
`Dir.chdir "../.." do sh("flutter", "build", "ios", "--release", "--codesign") end # Call Flutter Build
`
Source: https://flutter.dev/docs/deployment/cd

**Comment by tianhaoz95** [comment]
oh boy... I guess #88 copied it over.

Thanks for pointing that out!

I can add that back when my laptop is fixed... if you have some time, you can open a PR to fix that.

**Comment by tianhaoz95** [comment]
@all-contributors please add @lesliearkorful for bug
